version: '3.1'

services:

  postgres:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - 5500:8080
    networks: 
      - default

networks:
  default:
    driver: bridge


